### PR TITLE
add a script to clean useless generated txt files from assignements dump

### PR DESCRIPTION
**Pull request by ildyria**

### CODE REVIEW

**Comment by thomwiggers** [comment]
Huh, what is this? Are you deleting the `sXXXXXXX.txt` files? Those are the most useful thing this script collection provides...

**Comment by squell** [comment]
- These files are not useless!

- This script overwrites a script in the current directory. I would prefer a solution based on "xargs".

**Comment by thomwiggers** [comment]
Perhaps it is not clear as the [`LEESMIJ.txt`](https://github.com/squell/bb-scripts/blob/master/LEESMIJ.TXT) file is in Dutch, but those files are the core of providing studens with feedback through these scripts: you enter your feedback into those scripts (by adding a line with `Feedback:` followed by your feedback), and the assigned grade at `Current Grade:`. You can then automatically send the students send feedback by executing `feedback.sh`. This can also upgrade the grades to Blackboard.

**Comment by camilstaps** [comment]
Have a look at the simple branch; there is some printing functionality there (which I'm guessing you may find useful).

**Comment by MacGyverNL** [comment]
Two questions:

1. Why only remove when there are no student comments? Do you want the ones with student comments to remain?

2. Would a better solution be to suppress the creation of the .txt-files in the first place?

Regarding the script itself, seems to me that what you're doing should be as simple as
```grep -lZ "There are no ..." *.txt | xargs -0 rm```

**Comment by squell** [comment]
@thomwiggers Good point though - the LEESMIJ should probably be ported to English.

**Comment by squell** [comment]
I suggest adding the oneliner MacGyverNL proposes in bbfix.sh in your local clone, if the BlackBoard-response files are a hindrance. And as Camil states, the 'simple' branch might be more suitable in that case.

However, this feature will break the intended behaviour of the master branch fundamentally; closing!

**Pull request closed without merging**
