### PR TITLE
new rgrade.sh

### PR DESCRIPTION
**Pull request by dopefishh**
This version starts a program in the directory of a randomly selected submission.
- Are there arguments?

  run `$@`
- Is a `$SHELL` environment variable set

  run `$SHELL`
- If all the above fails

  run `bash`

### CODE REVIEW

**Comment by camilstaps** [comment]
It would be nice to still have the pdf option.

**Comment by dopefishh** [comment]
@camilstaps sure:
```
./rgrade.sh "evince *.pdf & vim -p *"
```

**Comment by camilstaps** [comment]
@dopefishh the original would kill the pdf reader when grading was finished (when the editor was closed).

**Comment by dopefishh** [comment]
if you are finished with grading the pdf just close the window

**Comment by camilstaps** [comment]
No. The whole purpose of these scripts is to ease the workflow. This PR may ease *your* workflow for the courses *you* assist in, but others assist in other courses where PDFs are accepted or even mandatory.

**Comment by squell** [comment]
If you switch the shell to bash instead of sh, you can use an exit-handler to kill background processes:

http://stackoverflow.com/questions/360201/how-do-i-kill-background-processes-jobs-when-my-shell-script-exits

**Comment by dopefishh** [comment]
all scripts that are sent to the graders are POSIX sh, let's keep it that way for maximum compatibility.

**Comment by dopefishh** [comment]
or you can do:
```
./rgrade 'evince *.pdf & PID=$! && vim -p s*.txt && kill $!'
```

**Comment by camilstaps** [comment]
That would work for me. I would still prefer to also have a BB_GRADECMD variable, but I can do that myself.

**Comment by squell** [comment]
@dopefishh The fact that only 'sh' is used is nice, but not by design. I wouldn't worry about bashisms if it adds functionality. That being said, the solution on stackexchange:

`trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT`

doesn't (seem to) require bash.

**Comment by camilstaps** [comment]
So I talked to @squell and he mentioned some ideas for this script that I will just list here:

- When exiting the editor, check if the file has a grade, and if not, ask the user if he wants to continue editing.
- A way to open a PDF reader and close it automatically which does not require a long argument.
- Putting everything in a while loop so that you don't need to run rgrade.sh over and over again.

Did I miss something? Anyway, this PR can be merged and these extensions can be added later.

**Comment by squell** [comment]
Not: the second bullet is simply related to the 'trap' thing. I don't know if adding the stackoverflow-solution could break the script, and I can't test it realistically, so I am hesitant to add it myself.

Thanks in any case. :)

**Pull request merged**
